#!/bin/bash
set -e

BUILD_TYPE=production
CACHE_RELOAD=no

while [ $# -gt 0 ]; do
    case "$1" in
        development | develop | dev )
            BUILD_TYPE=development
            ;;
        production | prod )
            BUILD_TYPE=production
            ;;
        --reload )
            CACHE_RELOAD=yes
            ;;
        * )
            echo "Usage: build [--reload] BUILD_TYPE"
            echo
            echo "BUILD_TYPE: production | prod (default)"
            echo "            development | develop | dev"
            false
    esac
    shift
done

IMPORT_MAP="--import-map import_map.json"
LOCK="--lock lock.json"
if [ "$BUILD_TYPE" = "development" ]; then
    IMPORT_MAP="--import-map dev_import_map.json"
    LOCK=""
fi

if [ "$CACHE_RELOAD" = "yes" ]; then
    LOCK_WRITE=""
    if [ "$LOCK" != "" ]; then
        LOCK_WRITE="--lock-write"
    fi
    deno cache --reload $LOCK_WRITE $LOCK $IMPORT_MAP app.tsx html.tsx serve.ts
fi

OUT_DIR=build
if [ "$BUILD_TYPE" = "development" ]; then
    OUT_DIR=dev_build
fi

rm -rf $OUT_DIR
mkdir -p "$OUT_DIR"
deno bundle $LOCK $IMPORT_MAP serve.ts "$OUT_DIR/serve.js"
deno bundle $LOCK $IMPORT_MAP app.tsx "$OUT_DIR/app.js"
deno run $LOCK $IMPORT_MAP html.tsx > "$OUT_DIR/app.html"
